### ISSUE TITLE
请问作者有尝试过将starEnhancer网络做单纯的增强吗

### ISSUE THREAD

**Issue by 906527105** [IDKiro/StarEnhancer#10]
不做风格迁移而是单纯的iamge retouching

**Comment by IDKiro** [comment]
你是不是指的单风格的增强，那就是我们的Basic Enhancer，我发现有好几个同学来问过，所以我把给它们的代码打包放在[release](https://github.com/IDKiro/StarEnhancer/releases/download/others/BasicEnhancer.zip)里了。

**Comment by 906527105** [comment]
这里面的slimEnhancer和Enhancer是对应的简化版本模型吗，我看git上也是这样的

**Comment by IDKiro** [comment]
StarEnhancer和Basic Enhancer的代码我都提供了SlimEnhancer和Enhancer，SlimEnhancer是Enhancer的简化版本，两个空间坐标的曲线都去除了，以及让所有曲线的量化深度都相同了。
这主要是因为两个空间坐标对最后结果影响比较小，然后不同的量化深度的曲线的变换用PyTorch原生算子实现需要引入循环，会稍微降低点速度（CUDA代码的license限制太多，就没开源）。

**Comment by IDKiro** [comment]
没有其他问题的话我先把issue关了，有其他问题reopen就行

**Comment by 906527105** [comment]
可以的哈，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IDKiro/StarEnhancer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 中午12:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IDKiro/StarEnhancer] 请问作者有尝试过将starEnhancer网络做单纯的增强吗 (Issue #10)



 没有其他问题的话我先把issue关了，有其他问题reopen就行

**Comment by 906527105** [comment]
原来如此，感谢哈


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "IDKiro/StarEnhancer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月25日(星期三) 上午10:58
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [IDKiro/StarEnhancer] 请问作者有尝试过将starEnhancer网络做单纯的增强吗 (Issue #10)



 StarEnhancer和Basic Enhancer的代码我都提供了SlimEnhancer和Enhancer，SlimEnhancer是Enhancer的简化版本，两个空间坐标的曲线都去除了，以及让所有曲线的量化深度都相同了。
 这主要是因为两个空间坐标对最后结果影响比较小，然后不同的量化深度的曲线的变换用PyTorch原生算子实现需要引入循环，会稍微降低点速度（CUDA代码的license限制太多，就没开源）。
