### ISSUE TITLE
About pretrain model

### ISSUE THREAD

**Issue by hhhhnwl** [IDKiro/StarEnhancer#12]
提供的pretrain模型可以直接跑出enhancer的效果吗，还是说必须先加载进来训练呢，我发现直接加载pretrain的模型跑出的图片没有什么效果。

**Comment by IDKiro** [comment]
没太搞懂你的问题。
提供的模型权重准确来讲就是训练好的模型，请确保文件放在正确的路径并进行加载。
注意模型分为四个部分，测试时至少要加载enhancer、mapping的网络权重以及风格表征的embedding文件。
