### ISSUE TITLE
One question about the code under the setting of sigle-style enhancement

### ISSUE THREAD

**Issue by HangLuoWh** [IDKiro/StarEnhancer#13]
I am testing your codes on single-style enhancement. However, in line 103-104 of the file 'loader.py', I find you randomly use images of different styles as the source image and target image during the training and validation stage, which may cause the optimization process unstable. It is better to fix the source style and target style?

**Comment by IDKiro** [comment]
StarEnhancer in the single-style enhancement experiment is trained on a multi-style dataset and tested on a single-style dataset (BasicEnhancer, on the other hand, was trained and tested on a single-style dataset). Therefore, during training, the model needs to adapt to different and randomized style embeddings. 

But you are correct regarding inference. During testing, the embedding sequence used was extracted from the training images, resulting in a length of 4500. The random.sample function was then used to extract 500 samples without replacement, introducing randomness. From the experimental results, the impact of this randomness is minimal, as the average embedding of the 500 samples can still approximate the average embedding of that style quite well. The printed results (the open-source model is retrained) should be:

```
PSNR: 22.86 (25.41)	SSIM: 0.930 (0.942)	LPIPS: 0.106 (0.085)
```

However, from the perspective of experimental rigor, it is necessary to correct this part of the code. 

Thank you very much for your question.
