### ISSUE TITLE
使用GAN进行非成对训练是否可行？

### ISSUE THREAD

**Issue by FightingSrain** [IDKiro/StarEnhancer#6]
非常感谢您开源代码！
您是否进行过，使用GAN进行非成对训练的实验，这样是否可行，您对此有什么看法吗？

**Comment by IDKiro** [comment]
可行，我做过，是可以训练出来的。
单风格做起来比较简单，直接用cyclegan训练就能到PSNR 22左右，但是多风格训练并不容易，需要加一些对于颜色的正则，不然最后效果不太理想。
我论文里没写这部分，一方面是因为GAN训练出来效果并不好，比监督差很多。另一方面是，我提出的方法就是为了解决训练数据集收集困难的问题，再用GAN就画蛇添足了。

**Comment by FightingSrain** [comment]
非常感谢您的回答！单一的判别器也许无法很好的学到风格，那么如果将明度色度分开，用两个鉴别器，分别学习，这样也许可以提高效果，这只是一个简单的想法，您对此有什么看法呢?

**Comment by IDKiro** [comment]
我训练的时候，比较类似StarGAN的思路，风格分类器+单个D，效果比较一般，你可以做参考。
多个D分别监督不同的分量，算是一种引入人为先验的方式，应该会有一定效果，但是效果不会明显。我认为可以作为正则，但是想要以此取得明显进步，可能不太可行。

**Comment by FightingSrain** [comment]
谢谢您的解答！
