### ISSUE TITLE
数据集处理

### ISSUE THREAD

**Issue by madfff** [IDKiro/StarEnhancer#7]
你好，我在您提供的fivek.lrcat没找到  DeepUPE issue里的"(default) input with ExpertC"。请问单风格实验的输入是下图中的“InputAsShotZeroed”还是“(Q)InputZeroed with ExpertC WhiteBalance”
![image](https://user-images.githubusercontent.com/48885534/150954251-6265fc4b-9edf-4f41-8b78-12b54fa468f3.png)

**Comment by IDKiro** [comment]
是(O)

**Comment by madfff** [comment]
感谢及时的回复
