### ISSUE TITLE
多风格，非配对图场景

### ISSUE THREAD

**Issue by jxust01** [IDKiro/StarEnhancer#8]
您好，在多风格非配对图场景，能否交换source和target的位置，并将得到的output_A和output_B进一步经过enhancer,得到recover_A和recover_B。最后计算l1_loss(source, recover_A)和l1_loss(target, recover_B)及Triplet_loss(output_A，target, source) 和 Triplet_loss(output_B，source，target)
```
def train(train_loader, mapping, enhancer, criterion, optimizer):
    losses = AverageMeter()
    criterionTriplet = torch.nn.TripletMarginLoss(margin=1.0, p=2)
    FEModel = Feature_Extract_Model().cuda()

    mapping.train()
    enhancer.train()

    for (source_img, source_center, target_img, target_center) in train_loader:
        source_img = source_img.cuda(non_blocking=True)
        source_center = source_center.cuda(non_blocking=True)
        target_img = target_img.cuda(non_blocking=True)
        target_center = target_center.cuda(non_blocking=True)

        style_A = mapping(source_center)
        style_B = mapping(target_center)

        output_A = enhancer(source_img, style_A, style_B)
        output_B = enhancer(target_img, style_B, style_A)
        recoverA = enhancer(output_A, style_B, style_A)
        recoverB = enhancer(output_B, style_A, style_B)

        source_img_feature = FEModel(source_img)
        target_img_feature = FEModel(target_img)
        output_A_feature = FEModel(output_A)
        output_B_feature = FEModel(output_B)

        loss_l1 = criterion(recoverA, source_img) + criterion(recoverB, target_img)
        loss_triplet = criterionTriplet(output_B_feature, source_img_feature, target_img_feature) + \
                       criterionTriplet(output_A_feature, target_img_feature, source_img_feature)
        loss = loss_l1 + loss_triplet

        losses.update(loss.item(), args.t_batch_size)

        optimizer.zero_grad()
        loss.backward()
        optimizer.step()

    return losses.avg
```

**Comment by IDKiro** [comment]
不知道我又没有理解对，你是想把CycleGAN的循环一致性约束加进去。在我做StarEnhancer的时候是不起作用的，但是后来我的一个未发表新工作（结构上有差别）又显示它可以提点。所以我也尚不清楚循环一致性约束的起效条件，但是我觉得你可以自行尝试一下，还是有希望提点的。
至于Triplet loss这种正负样本损失，在我的实验中是没有明显效果的。

**Comment by jxust01** [comment]
是的，因为没有配对图，所以想尝试CycleGAN的思路，但是经过几次enhancer后，recover和source在rgb2lab后计算L1loss时会出问题。
`/opt/conda/conda-bld/pytorch_1603728993639/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [374,0,0], thread: [10,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
/opt/conda/conda-bld/pytorch_1603728993639/work/aten/src/ATen/native/cuda/ScatterGatherKernel.cu:115: operator(): block: [374,0,0], thread: [14,0,0] Assertion `idx_dim >= 0 && idx_dim < index_size && "index out of bounds"` failed.
Traceback (most recent call last):
  File "train_enhancer_triplet.py", line 139, in <module>
    loss = train(train_loader, mapping, enhancer, criterion, optimizer)
  File "train_enhancer_triplet.py", line 64, in train
    loss_l1 = criterion(recoverA, source_img) + criterion(recoverB, target_img)
  File "/simple/zlp1/miniconda3/envs/py365/lib/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/simple/zlp1/masters/StarEnhancer/model/loss.py", line 56, in forward
    out_lab = self.rgb2lab(out_image)
  File "/simple/zlp1/masters/StarEnhancer/model/loss.py", line 48, in rgb2lab
    img[(img != img).detach()] = 0
RuntimeError: CUDA error: device-side assert triggered
`

**Comment by IDKiro** [comment]
这好像是内存索引超边界了，远程排查比较困难，你尝试一下：
1. lab上的L1 loss换成rgb上的L1 loss，也就是不经过rgb2lab这一步
2. 预测曲线参数的网络最后添加tanh，确保output的值域在[-1, 1]，否则recover的时候输入超出了曲线的输入值域
3. FEModel看上去是一个类似perceptual loss那样的预训练模型，尝试去掉相关的内容

**Comment by jxust01** [comment]
好的，1、3方法实验过是ok的，2中方法我去试试。谢谢您的解答！
