### ISSUE TITLE
Test

### ISSUE THREAD

**Issue by 33KU** [IDKiro/StarEnhancer#9]
Hi!
If I want to test my images with your pretrained model, where should I put my images?

**Comment by IDKiro** [comment]
This open source code does not support this feature.

If you want to use it to transform other styles, please rename your image set (such as `11-mystyle`) and put it in the `train` (downsampled images may be better) and `test` folder, then delete the original `embeddings.npy`, then run `python fetch_embedding.py` to generate new style code.

After that, run `python test.py --source_id 11` to transform your image (from your style (id 11) to default target style (id 3).
